version: '3'
services:
  db:
    image: postgres
    env_file:
      - path: ./backend/.env.development
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./database:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis
    env_file:
      - path: ./backend/.env.development
    ports:
        - ${REDIS_PORT}:6379
# run command: docker compose --env-file backend/.env up -d
# build command: docker compose --env-file backend/.env build
# stop command: docker compose down