name: Advanced authentication

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run lint
        run: npm run lint
        working-directory: ./backend

      - name: Run unit tests
        run: npm run test
        working-directory: ./backend

      - name: Run e2e tests
        run: npm run test:e2e
        working-directory: ./backend

      - name: Check tests coverage
        run: npm run test:cov
        working-directory: ./backend

      - name: Build project
        run: npm run build
        working-directory: ./backend

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage-report
          path: backend/coverage